# Generated by Django 3.1.4 on 2021-01-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210102_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='course_id',
        ),
        migrations.AddField(
            model_name='subjects',
            name='course_objects',
            field=models.ManyToManyField(to='pages.Courses'),
        ),
    ]
