# Generated by Django 3.1.4 on 2021-01-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210103_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='course_objects',
        ),
        migrations.AddField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.courses'),
            preserve_default=False,
        ),
    ]
